;;; rimel-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from rimel.el

(autoload 'rimel-activate "rimel"
"Activate rimel input method.
Called by Emacs when user selects the \"rimel\" input method.
_NAME is the input method name (unused).

(fn NAME)")
 (autoload 'rimel-select-schema "rimel" "Select a rime schema interactive." t)
 (autoload 'rimel-deploy "rimel" "Deploy liberime to affect config file change." t)
 (autoload 'rimel-sync "rimel" "Sync rime user data." t)
(register-input-method "rimel" "Chinese" #'rimel-activate (if (char-displayable-p 12563) (char-to-string 12563) "中") "Rimel - Rime input method via liberime")
(register-definition-prefixes "rimel" '("rimel-"))

;;; End of scraped data

(provide 'rimel-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; rimel-autoloads.el ends here
